### PR TITLE
Fetch upstream

### PR DESCRIPTION
**Pull request by jamesbt365**

### CODE REVIEW

**Comment by 32-bit-link** [comment]
how many bugs will this add?

**Comment by jamesbt365** [comment]
Let me check

**Comment by jamesbt365** [comment]
A small ui one afaik

**Comment by 32-bit-link** [comment]
any more?

**Comment by jamesbt365** [comment]
that seems to be it that i have discovered.

**Comment by jamesbt365** [comment]
Might be more

**Comment by 32-bit-link** [comment]
Acceptable.

**Pull request merged**
